FROM ruby:2.3
ENV LANG C.UTF-8
ENV RAILS_ENV local # set the environment
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs less

# alias
RUN echo 'alias ll="ls -laG"' >> /root/.bashrc

ENV APP_HOME /usr/src/app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/

ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile \
  BUNDLE_JOBS=2 \
  BUNDLE_PATH=/usr/local/bundle
ADD . $APP_HOME
