version: "2"
services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/usr/local/bundle
      - db:/var/lib/mysql
  db:
    image: mysql:5.7
    env_file: config/.local_env
    ports:
      - 3306:3306
    volumes_from:
      - datastore
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    volumes_from:
      - datastore
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    env_file: config/.local_env
    depends_on:
      - db

volumes:
  bundle_install:
    driver: local
  db:
    driver: local
